### ISSUE TITLE
Travis CI Arm64: No system-wide Python was found

### ISSUE THREAD

**Issue by arnaudh** [invenia/FTPServer.jl#22]
Most recent two Arm64 jobs failed:
- https://travis-ci.com/github/invenia/FTPServer.jl/jobs/379290407
- https://travis-ci.com/github/invenia/FTPServer.jl/jobs/379682188

Stack trace:
```python
┌ Error: Error building `PyCall`: 
│ Traceback (most recent call last):
│   File "<string>", line 1, in <module>
│   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
│   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
│   File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
│   File "<frozen importlib._bootstrap>", line 577, in module_from_spec
│   File "/home/travis/.local/lib/python3.5/site-packages/_distutils_hack/__init__.py", line 82, in create_module
│     return importlib.import_module('._distutils', 'setuptools')
│   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
│     return _bootstrap._gcd_import(name[level:], package, level)
│   File "<frozen importlib._bootstrap>", line 981, in _gcd_import
│   File "<frozen importlib._bootstrap>", line 931, in _sanity_check
│ SystemError: Parent module 'setuptools' not loaded, cannot perform relative import
│ ERROR: LoadError: No system-wide Python was found; got the following error:
│ ProcessFailedException(Base.Process[Process(setenv(`python3 -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`,["TRAVIS_OSX_IMAGE=", "DOCUMENTER_KEY=[secure]", "PATH=/home/travis/bin:/home/travis/.local/bin:/home/travis/.rvm/gems/ruby-2.7.0/bin:/home/travis/.rvm/gems/ruby-2.7.0@global/bin:/home/travis/.rvm/rubies/ruby-2.7.0/bin:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.kiex/elixirs/elixir-1.9.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/travis/.phpenv/bin:/home/travis/.rvm/bin:/home/travis/julia/bin:/home/travis/julia/bin", "TRAVIS_BRANCH=master", "SUDO_GID=0", "TRAVIS_SUDO=true", "TRAVIS_ALLOW_FAILURE=", "TRAVIS_TMPDIR=/tmp/tmp.XR48CScrXT", "TRAVIS_JOB_NUMBER=379.12", "TRAVIS_PULL_REQUEST_SHA=", "TRAVIS_TIMER_ID=08472178", "TRAVIS_INIT=systemd", "MANPATH=/home/travis/.nvm/versions/node/v8.12.0/share/man:/home/travis/.kiex/elixirs/elixir-1.9.1/man:/usr/local/man:/usr/local/share/man:/usr/share/man", "TRAVIS_BUILD_ID=182161194", "TRAVIS_PULL_REQUEST_SLUG=", "TRAVIS_SECURE_ENV_VARS=true", "MYSQL_UNIX_PORT=/var/run/mysqld/mysqld.sock", "TRAVIS_BUILD_NUMBER=379", "NVM_CD_FLAGS=", "SUDO_USER=root", "ANSI_CLEAR=\\033[0K", "CONTINUOUS_INTEGRATION=true", "TRAVIS_TEST_RESULT=", "TRAVIS_BUILD_STAGE_NAME=test", "SUDO_COMMAND=/bin/bash /home/travis/build.sh", "TRAVIS_INTERNAL_RUBY_REGEX=^ruby-(2\\.[0-4]\\.[0-9]|1\\.9\\.3)", "MIX_ARCHIVES=/home/travis/.kiex/mix/elixir-1.9.1", "ANSI_GREEN=\\033[32;1m", "USER=travis", "PS4=+", "rvm_version=1.29.10 (latest)", "ELIXIR_VERSION=1.9.1", "TRAVIS_JULIA_VERSION=1", "JULIA_PROJECT=@.", "TRAVIS_PULL_REQUEST=false", "USERNAME=travis", "APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1", "TRAVIS_TIMER_START_TIME=1598915541842480381", "JL_PKG=FTPServer", "XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop", "TRAVIS_PULL_REQUEST_BRANCH=", "TRAVIS_JOB_ID=379682188", "SHELL=/bin/bash", "TRAVIS_TAG=", "TRAVIS_ROOT=/", "RUBY_VERSION=ruby-2.7.0", "container=lxc", "NVM_DIR=/home/travis/.nvm", "NVM_BIN=/home/travis/.nvm/versions/node/v8.12.0/bin", "DEBIAN_FRONTEND=noninteractive", "TERM=xterm", "HOME=/home/travis", "PYTHONIOENCODING=UTF-8", "TRAVIS_APP_HOST=build.travis-ci.com", "rvm_path=/home/travis/.rvm", "TRAVIS_OS_NAME=linux", "TRAVIS_ENABLE_INFRA_DETECTION=true", "rvm_prefix=/home/travis", "GIT_ASKPASS=echo", "PERLBREW_SHELLRC_VERSION=0.88", "TRAVIS_ARCH=aarch64", "LANG=C.UTF-8", "SHLVL=1", "LOGNAME=travis", "TRAVIS_FILTERED=redirect_io", "rvm_bin_path=/home/travis/.rvm/bin", "TRAVIS_APT_PROXY=http://build-cache.travisci.net", "OLDPWD=/home/travis/build", "IRBRC=/home/travis/.rvm/rubies/ruby-2.7.0/.irbrc", "TRAVIS_REPO_SLUG=invenia/FTPServer.jl", "GEM_PATH=/home/travis/.rvm/gems/ruby-2.7.0:/home/travis/.rvm/gems/ruby-2.7.0@global", "ANSI_RED=\\033[31;1m", "PAGER=cat", "TRAVIS_COMMIT=7cc92c49c96555c6d88db8df4770c638a0d37dd1", "TRAVIS_COMMIT_RANGE=ff11bdbdd9da9e1fd5d4ee0ffc8f99b8dad0f229...7cc92c49c96555c6d88db8df4770c638a0d37dd1", "_=/home/travis/julia/bin/julia", "SYS_PYTHON=", "ANSI_RESET=\\033[0m", "PERLBREW_HOME=/home/travis/.perlbrew", "TRAVIS_CPU_ARCH=arm64", "PERLBREW_ROOT=/home/travis/perl5/perlbrew", "TRAVIS_EVENT_TYPE=cron", "PWD=/home/travis/build/invenia/FTPServer.jl", "OPENBLAS_NUM_THREADS=8", "MY_RUBY_HOME=/home/travis/.rvm/rubies/ruby-2.7.0", "TRAVIS_COMMIT_MESSAGE=Set project version to 0.3.1", "CI=true", "TRAVIS_CMD=julia --color=yes -e \"if VERSION < v\\\"0.7.0-DEV.5183\\\"; Pkg.clone(pwd()); Pkg.build(\\\"\${JL_PKG}\\\"); else using Pkg; if VERSION >= v\\\"1.1.0-rc1\\\"; Pkg.build(verbose=true); else Pkg.build(); end; end\"", "GEM_HOME=/home/travis/.rvm/gems/ruby-2.7.0", "TRAVIS_BUILD_WEB_URL=https://travis-ci.com/invenia/FTPServer.jl/builds/182161194", "TRAVIS_INFRA=unknown", "TRAVIS_LANGUAGE=julia", "SUDO_UID=0", "TRAVIS_JOB_WEB_URL=https://travis-ci.com/invenia/FTPServer.jl/jobs/379682188", "TRAVIS_HOME=/home/travis", "TRAVIS_BUILD_DIR=/home/travis/build/invenia/FTPServer.jl", "JULIA_LOAD_PATH=@:/tmp/jl_aagg5I", "TRAVIS_JOB_NAME=", "TRAVIS=true", "ANSI_YELLOW=\\033[33;1m", "HAS_JOSH_K_SEAL_OF_APPROVAL=true", "OPENBLAS_MAIN_FREE=1", "TRAVIS_DIST=xenial"]), ProcessExited(1))])
│ Stacktrace:
│  [1] error(::String, ::String) at ./error.jl:42
│  [2] top-level scope at /home/travis/.julia/packages/PyCall/zqDXB/deps/build.jl:77
│  [3] include(::String) at ./client.jl:457
│  [4] top-level scope at none:5
│ in expression starting at /home/travis/.julia/packages/PyCall/zqDXB/deps/build.jl:43
│ caused by [exception 1]
│ failed process: Process(setenv(`python3 -c "import distutils.sysconfig; print(distutils.sysconfig.get_config_var('VERSION'))"`,["TRAVIS_OSX_IMAGE=", "DOCUMENTER_KEY=[secure]", "PATH=/home/travis/bin:/home/travis/.local/bin:/home/travis/.rvm/gems/ruby-2.7.0/bin:/home/travis/.rvm/gems/ruby-2.7.0@global/bin:/home/travis/.rvm/rubies/ruby-2.7.0/bin:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.kiex/elixirs/elixir-1.9.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/travis/.phpenv/bin:/home/travis/.rvm/bin:/home/travis/julia/bin:/home/travis/julia/bin", "TRAVIS_BRANCH=master", "SUDO_GID=0", "TRAVIS_SUDO=true", "TRAVIS_ALLOW_FAILURE=", "TRAVIS_TMPDIR=/tmp/tmp.XR48CScrXT", "TRAVIS_JOB_NUMBER=379.12", "TRAVIS_PULL_REQUEST_SHA="  …  "TRAVIS_JOB_WEB_URL=https://travis-ci.com/invenia/FTPServer.jl/jobs/379682188", "TRAVIS_HOME=/home/travis", "TRAVIS_BUILD_DIR=/home/travis/build/invenia/FTPServer.jl", "JULIA_LOAD_PATH=@:/tmp/jl_aagg5I", "TRAVIS_JOB_NAME=", "TRAVIS=true", "ANSI_YELLOW=\\033[33;1m", "HAS_JOSH_K_SEAL_OF_APPROVAL=true", "OPENBLAS_MAIN_FREE=1", "TRAVIS_DIST=xenial"]), ProcessExited(1)) [1]
│ 
│ Stacktrace:
│  [1] pipeline_error at ./process.jl:525 [inlined]
│  [2] read(::Cmd) at ./process.jl:412
│  [3] read(::Cmd, ::Type{String}) at ./process.jl:421
│  [4] pyvar(::String, ::String, ::String) at /home/travis/.julia/packages/PyCall/zqDXB/deps/buildutils.jl:6
│  [5] pyconfigvar at /home/travis/.julia/packages/PyCall/zqDXB/deps/buildutils.jl:8 [inlined]
│  [6] pyconfigvar(::String, ::String, ::String) at /home/travis/.julia/packages/PyCall/zqDXB/deps/buildutils.jl:9
│  [7] top-level scope at /home/travis/.julia/packages/PyCall/zqDXB/deps/build.jl:45
│  [8] include(::String) at ./client.jl:457
│  [9] top-level scope at none:5
└ @ Pkg.Operations /buildworker/worker/package_linuxaarch64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:949
```

**Comment by arnaudh** [comment]
Diffing the job output with the previous succeeding one, I see:
```diff
-Build id: 181922544
-Job id: 379137250
-Runtime kernel version: 5.3.0-24-generic
+Build id: 181987329
+Job id: 379290407
+Runtime kernel version: 5.3.0-40-generic
```

Maybe this is related, and `5.3.0-40-generic` has a different Python installation?

**Comment by arnaudh** [comment]
Seems to be intermittent, issue went away and the latest job succeeded: https://travis-ci.com/github/invenia/FTPServer.jl/jobs/380108184

**Comment by iamed2** [comment]
I noticed the successful one you posted has `Runtime kernel version: 5.3.0-42-generic`

I don't see how this linux kernel version could impact the availability of Python or Python modules but it's possible that Travis broke something in their build system that they then fixed?

**Comment by arnaudh** [comment]
Quite probable. Daily builds are passing now, closing the issue.
